### ISSUE TITLE
Query iterator should return timestamp column values as `time.Time`

### ISSUE THREAD

**Issue by alespour** [InfluxCommunity/influxdb3-go#32]
### Use Case

`time.Time` is Golang native type for time/timestamp. Now user has to do this:

```go
	value := iterator.Value()
	timestamp := value["time"].(arrow.Timestamp).ToTime(arrow.Nanosecond)
```

### Expected behavior

Golang type for timestamp should be `time.Time`

### Actual behavior

Time is of `arrow.Timestamp`

**Comment by bednar** [comment]
From my POV I would like to keep the basic query implementation as simple as possible. This enhancement can be done in our improvement: [Query data to Structured Object](https://github.com/orgs/influxdata/projects/108/views/1?pane=issue&itemId=31487801)
