### ISSUE TITLE
Add query method returning unprocessed result from flightsql client 

### ISSUE THREAD

**Issue by alespour** [InfluxCommunity/influxdb3-go#33]
### Use Case

Give the user option to process the result as deems best without any processing by the package itself. Such option exists in other client libs.

### Expected behavior

Return "raw" query result.

### Actual behavior

Only iterator over array(s) created by the implementation from flightsql reader is returned.

**Comment by redbaron** [comment]
There seem to be https://pkg.go.dev/github.com/InfluxCommunity/influxdb3-go@v0.3.0/influxdb3#QueryIterator.Raw now

**Comment by bednar** [comment]
@redbaron you are right, thanks!
