### ISSUE TITLE
write: a collection of generic interfaces

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-go#62]
### Use Case

Currently the Write API has the methods. 

```go
func (c *Client) WriteData(ctx context.Context, points ...interface{}) error { ... }
```
and 

```go
func (c *Client) WriteDataWithOptions(ctx context.Context, options *WriteOptions, points ...interface{}) error {...}
```
It would also be useful to be able to write batches/collections of a generic interface type. 

### Expected behavior

When I've a collection of objects of a local type, I would like to write them in one call using the `points ...inteface{}` idiom.  

### Actual behavior

Currently this requires repeated calls, in a loop to one of the methods mentioned under **Use Case**

### Additional info

I've made  a simple sequential implementation of this locally.

```go
func WriteBatchDataSeq[T any](client *influxdb3.Client,
	ctx context.Context,
	opts *influxdb3.WriteOptions,
	ifaces []T) error {

	for _, iface := range ifaces {
		fmt.Printf("%s %v\n", reflect.TypeOf(iface).Kind().String(), iface)
		err := client.WriteDataWithOptions(ctx, opts, iface)
		if err != nil {
			return err
		}
	}
	return nil
}
```

**Comment by karel-rehor** [comment]
Only as a reminder 
```go
werr := client.WriteDataWithOptions(context.Background(), &wopts, []interface{})
```
... throws error like...

```
error encoding point: cannot use []main.Nautilus as point
```
and 

```go
werr := client.WriteDataWithOptions(context.Background(), &wopts, []interface{})
```
...throws error like...

```
error encoding point: cannot use []*main.Nautilus as point
```

**Comment by bednar** [comment]
@thulasirajkomminar thanks for clarify your interesting, we will prioritise this issue. 

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

**Comment by thulasirajkomminar** [comment]
> @thulasirajkomminar thanks for clarify your interesting, we will prioritise this issue.
> 
> Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

I think @karel-rehor already made some commits for this https://github.com/InfluxCommunity/influxdb3-go/compare/feat/writeIfaceArray

**Comment by alespour** [comment]
User can use `client.WriteData(ctx, points...)` when the collection of annotated structs is a `[]interface{}` slice. If there is a need to keep the points in strongly typed slice, [conversion to slice of interfaces](https://go.dev/doc/faq#convert_slice_of_interface) is straightforward.
I'm for closing this with `wontfix` label. Other opinions?

**Comment by bednar** [comment]
> User can use `client.WriteData(ctx, points...)` when the collection of annotated structs is a `[]interface{}` slice. If there is a need to keep the points in strongly typed slice (`[]T`), [conversion to slice of interfaces](https://go.dev/doc/faq#convert_slice_of_interface) is straightforward.
> 

@alespour nice hint 👍 

> I'm for closing this with `wontfix` label. Other opinions?

I agree

**Comment by thulasirajkomminar** [comment]
@bednar @alespour I created my own function to convert my custom slice to slice of any so I think the issue can be closed.
