### ISSUE TITLE
QueryType constant should be `SQL` instead of `FlightSQL`

### ISSUE THREAD

**Issue by jstirnaman** [InfluxCommunity/influxdb3-go#70]
Because the client uses the (IOx native) Flight RPC API, and not FlightSQL, shouldn't the `QueryType` be `SQL`? It makes explaining the distinctions even more confusing--for example:

- "native" Flight API and FlightSQL are different APIs built on the same protocol
- you can use SQL with this client
- you're not using FlightSQL, although the default QueryType here suggests that you are:

https://github.com/InfluxCommunity/influxdb3-go/blob/5bbcc4a45b993a5db7a746475cff6bad8a70f0d4/influxdb3/query_type.go#L30

**Comment by bednar** [comment]
@jstirnaman you are right, I will fix this inconsistency ASAP
