### ISSUE TITLE
`SetTag` function uses print function instead of logger

### ISSUE THREAD

**Issue by thulasirajkomminar** [InfluxCommunity/influxdb3-go#73]
### Specifications

* Package Version: v0.6.0
* InfluxDB Version: V3
* Platform: 

### Code sample to reproduce problem

```go
WriteData(context.Background(), []any{measurement})
```

Some measurement has empty tags and some don't. The Write method should use a logger to warn for the empty values but instead it prints the warning which we cannot control over. This will result in lot of logs.

### Expected behavior

Should only print the empty tag as warning

### Actual behavior

```
2024-04-02T18:53:19.013+02:00	Empty tags has no effect, tag [*****], measurement [*****]
2024-04-02T18:53:19.013+02:00	Empty tags has no effect, tag [*****], measurement [*****]
2024-04-02T18:53:19.013+02:00	Empty tags has no effect, tag [*****], measurement [*****]
2024-04-02T18:53:19.013+02:00	Empty tags has no effect, tag [*****], measurement [*****]
2024-04-02T18:53:19.013+02:00	Empty tags has no effect, tag [*****], measurement [*****]
```

### Additional info
Code block https://github.com/InfluxCommunity/influxdb3-go/blob/main/influxdb3/point_values.go#L73
_No response_

**Comment by bednar** [comment]
Hi @thulasirajkomminar,

thanks for using our client. 

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Best Regards

**Comment by thulasirajkomminar** [comment]
> Hi @thulasirajkomminar,
> 
> thanks for using our client.
> 
> Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.
> 
> Best Regards

@bednar Mirrored V2 log implementation https://github.com/InfluxCommunity/influxdb3-go/pull/74
