### ISSUE TITLE
Support management api

### ISSUE THREAD

**Issue by thulasirajkomminar** [InfluxCommunity/influxdb3-go#82]
The new V3 management api lets the user manage databases and database tokens. Is it already in the roadmap to implement this?

**Comment by bednar** [comment]
Hi @thulasirajkomminar,

Thank you for your suggestions! We have added these requirements to our backlog. As of now, we do not have a specific timeline for when we will start working on these enhancements.

Given the situation, would you be interested in contributing to the development of these features? We greatly appreciate community involvement and would be thrilled to collaborate with you on this. If you're interested, please let us know.

Best Regards

**Comment by thulasirajkomminar** [comment]
@bednar Yes working on it. Shall I create a PR in this repo or do you want the management api in a new repo?

**Comment by bednar** [comment]
Feel free to create PR in this repo.

**Comment by xorphitus** [comment]
Although it's still a draft, I've made a minimum PR #86.

**Comment by bednar** [comment]
Some management features were implemented by #87 and #86. Please feel free to extend these contributions if they do not cover your requirements.
